version: "3.8"

services:
  mysql:
    image: mysql:8.0.43
    container_name: inventory-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: inventorydb
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    ports:
      - "2704:3306"
    volumes:
      - inventory-mysql-data:/var/lib/mysql
    networks:
      - backend

  inventory-service:
    build:
      context: ./
    container_name: inventory-service
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/inventorydb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8083:8083"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  inventory-mysql-data:
