version: '3.8'
services:
  mysql:
    image: mysql:8.0.43-debian
    container_name: ps_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: payment_db
      MYSQL_ROOT_PASSWORD: "0942868460"
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init_database.sql:/docker-entrypoint-initdb.d/init_database.sql
    networks:
      - ps_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ps_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ps_network

  payment-service:
    build:
      context: ./ 
    container_name: payment-service
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/payment_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 0942868460
      RABBIT_HOST: rabbitmq
      RABBIT_PORT: 5672
      RABBIT_USERNAME: guest
      RABBIT_PASSWORD: guest
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8082:8080"
    depends_on:
      - mysql
      - rabbitmq
    networks:
      - ps_network

volumes:
  mysql_data:

networks:
  ps_network:
    driver: bridge
