server:
  port: 3000 
spring:
  application:
    name: order-service # Tên đăng ký với Eureka (khớp với Gateway)

  # Cấu hình CSDL (MySQL)
  datasource:
    # 'mysql' là tên service trong docker-compose.yml
    url: jdbc:mysql://localhost:3306/order_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC}
    username: root
    password: ${SPRING_DATASOURCE_PASSWORD:rootpassword}
  jpa:
    hibernate:
      ddl-auto: update # Tự động cập nhật bảng
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  # Cấu hình RabbitMQ
  rabbitmq:
    host: localhost # 'rabbitmq' là tên service trong docker-compose.yml

# Cấu hình Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

# Tên hàng đợi
queue:
  name: PAYMENT_COMPLETED_QUEUE