server:
  port: 8080

spring:
  application:
    name: api-gateway
  
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**, /users/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /users/${segment}

        - id: package-service
          uri: lb://package-service   
          predicates:
            - Path=/api/packages/** 
          filters:
            - RewritePath=/api/packages/(?<segment>.*), /packages/${segment}

        - id: battery-service
          uri: lb://battery-service
          predicates:
            - Path=/batteries/**
            
        - id: station-service
          uri: lb://station-service
          predicates:
            - Path=/stations/**
    
        - id: payment-service-secured
          uri: lb://paymentservice
          predicates:
            - Path=/payment/transactions
          filters:
            - RewritePath=/payment/(?<segment>.*), /${segment}
            # - AuthenticationFilter
        
      
        - id: payment-service-webhook
          uri: lb://paymentservice
          predicates:
            - Path=/payment/sepay_webhook
          filters:
            - RewritePath=/payment/(?<segment>.*), /${segment}
        
      
        - id: payment-service-simulate
          uri: lb://paymentservice
          predicates:
            - Path=/payment/simulate-success
          filters:
            - RewritePath=/payment/(?<segment>.*), /${segment}

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/** , /orders
          filters:
            - RewritePath=/orders/(?<segment>.*), /${segment}
            - RewritePath=/orders, /
            # - AuthenticationFilter

        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/booking/**
          filters:
            - RewritePath=/api/booking/(?<segment>.*), /${segment}
            # - AuthenticationFilter

      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns:
              - "http://localhost:3000"
              - "http://localhost:5173"
              - "exp://localhost:19000"
              - "http://192.168.1.*:19000"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: true

# Eureka Client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
# Logging
logging:
  level:
    com.example: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.cors: DEBUG