version: "3.8"

services:
  mysql:
    image: mysql:8.0.43
    container_name: transaction-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: transaction_db
    ports:
      - "3306:3306"
    volumes:
      - transaction-mysql-data:/var/lib/mysql
    networks:
      - backend

  transaction-service:
    build:
      context: ./
    container_name: transaction-service
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/transaction_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8082:8082"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  transaction-mysql-data:
