services:
  mysql-db:
    image: mysql:8.0
    container_name: station-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: station_management
      MYSQL_USER: station_user
      MYSQL_PASSWORD: station_password
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - station-network

    healthcheck:  # healthcheck cho việc biết khi db đã hoạt động
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_password"]
      timeout: 20s
      retries: 10
      interval: 30s
      start_period: 40s

  station-service:
    build: .
    image: ev-battery-swap-management-station-system/station-service
    container_name: station-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/station_management
      - SPRING_DATASOURCE_USERNAME=station_user
      - SPRING_DATASOURCE_PASSWORD=station_password
    depends_on:
      mysql-db:
        condition: service_healthy  # Chờ đến khi database chạy
    networks:
      - station-network
    healthcheck:  #healthcheck
      test: ["CMD-SHELL", "curl -f http://localhost:8082/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  mysql_data:

networks:
  station-network:
    driver: bridge