version: '3.8'

services:
  mysql:
    image: mysql:8.0.43-debian
    container_name: os_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "0942868460"
      MYSQL_DATABASE: order_db
    ports:
      - "3303:3306" 
    volumes:
      - order_mysql_data:/var/lib/mysql
      - ./init_database.sql:/docker-entrypoint-initdb.d/init_database.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - os_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: os_rabbitmq
    restart: unless-stopped
    ports:
      - "5673:5672"     # host:container
      - "15673:15672"
    networks:
      - os_network

  order-service:
    build:
      context: ./ 
    container_name: order-service
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/order_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 0942868460

      RABBIT_HOST: rabbitmq
      RABBIT_PORT: 5672
      RABBIT_USERNAME: guest
      RABBIT_PASSWORD: guest
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - rabbitmq
    networks:
      - os_network

volumes:
  order_mysql_data:

networks:
  os_network:
    driver: bridge
