server:
  port: 3002

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payment_service?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC}
    username: root
    password: ${SPRING_DATASOURCE_PASSWORD:rootpassword}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Rabbit (docker-compose sẽ chạy rabbitmq)
  rabbitmq:
    host: localhost
    # port: ${RABBIT_PORT:5672}
    # username: ${RABBIT_USERNAME:guest}
    # password: ${RABBIT_PASSWORD:guest}

queue:
  name: PAYMENT_COMPLETED_QUEUE

sepay:
  webhook-secret: "spsk_test_A3mvDnHRPqw1fZ7S8rzN9J1UWaRT1PDF"
  
  bank-account: "68209022004"
  bank-name: "TPBank"
  default-description: "TKPDHD"
