server:
  port: 3000 
spring:
  application:
    name: order-service # Tên đăng ký với Eureka (khớp với Gateway)

  # Cấu hình CSDL (MySQL)
  datasource:
    url: "jdbc:mysql://mysql:3303/order_db"
    username: root
    password: 0942868460"
  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  # Cấu hình RabbitMQ
  rabbitmq:
    host: ${RABBIT_HOST:rabbitmq}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}


# Tên hàng đợi
queue:
  name: PAYMENT_COMPLETED_QUEUE